### ISSUE TITLE
Something is missing there

### ISSUE THREAD

**Issue by tczekajlo** [Miszcz-AndY/HELLO#1]
Hi man! 

This new repo looks pretty good, but I have this impression that something's missing there. I think one "KUKU" more in README file and it'll be perfect.

Have a nice day!

**Comment by jakubfi** [comment]
This is definitely a bug, but can be easily fixed with #2.

**Comment by andy-miszcz** [comment]
Sorry for delay in response - I'm really busy last time ...  

I accept this idea and your fix. I will merge it as there are a lot of conflicts.
